//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public bool IsActive { get; set; }
        public int ContactPersonId { get; set; }
        public int CustomerContactPersonTypeId { get; set; }
    
        public virtual ContactPerson ContactPerson { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
