//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecurity
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Password { get; set; }
        public bool IsLocked { get; set; }
        public int LoginAttempts { get; set; }
        public string KeyToken { get; set; }
        public System.DateTime TokenExpires { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual User User { get; set; }
    }
}
